name: Build and push to GH pages
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      WASI_SDK_PATH: /opt/wasi-sdk
    steps:
      - run: sudo apt install wget unzip
      - run: wget https://github.com/nesbox/TIC-80/releases/download/v1.1.2837/tic80-v1.1-linux.deb
      - run: wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-30/wasi-sdk-30.0-x86_64-linux.deb
      - run: sudo dpkg -i tic80-v1.1-linux.deb
      - run: sudo dpkg -i wasi-sdk-30.0-x86_64-linux.deb
      - uses: actions/checkout@v4
      - run: mkdir out
      - run: make export_web
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: build-artifact
          path: "./out"

      - name: Deploy preview (PRs to /pr)
        if: github.event_name == 'pull_request'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: out
          preview-branch: gh-pages
          qr-code: true

      - name: Deploy main (pushes to main -> /)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out

